### ISSUE TITLE
CPC - FileNotFoundError: [Errno 2] No such file or directory: './results/cpc/cpc-model_best.pth'

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#19]
Hello,

I run this code: python -u ./baseline.py --dataset UCR --model CPC  --debug > stdout_base_CPC 2>stderr_base_CPC

And I get this error:

Traceback (most recent call last):
  File "./baseline.py", line 761, in <module>
    main()
  File "./baseline.py", line 701, in main
    train_model(
  File "./baseline.py", line 334, in train_model
    train_scores, test_scores = evaluator.get_predict(
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/merlion/evaluate/anomaly.py", line 433, in get_predict
    train_result, result = super().get_predict(
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/merlion/evaluate/base.py", line 173, in get_predict
    train_result = self._train_model(train_vals, **full_train_kwargs)
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/merlion/evaluate/base.py", line 129, in _train_model
    return self.model.train(train_vals, **train_kwargs)
  File ".../COCA-main-December182023/COCA-main/models/CPC/DetectorModel.py", line 129, in train
    self._train(train_df.values)
  File ".../COCA-main-December182023/COCA-main/models/CPC/DetectorModel.py", line 74, in _train
    snapshot(self.config.logging_dir, 'cpc', {
  File ".../COCA-main-December182023/COCA-main/models/CPC/network/training_v1.py", line 78, in snapshot
    torch.save(state, snapshot_file)
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './results/cpc/cpc-model_best.pth'

Must I run another code before this? Please advise.

Marcia

**Comment by ruiking04** [comment]
This may be a problem with the pytorch version. We are working on it and will get back to you as soon as possible.

**Comment by marciahon29** [comment]
Please let me know when you correct it.

**Comment by ruiking04** [comment]
The reason is that in some versions of Pytorch, the path name cannot use '\\'. Modify as follows:
models/CPC/network/training_v1.py
![image](https://github.com/ruiking04/COCA/assets/98844439/926e0805-6879-47e2-a0da-11dde25adce0)
For specific problem analysis, please refer to: [problem analysis](https://stackoverflow.com/questions/2953834/how-should-i-write-a-windows-path-in-a-python-string-literal)

**Comment by marciahon29** [comment]
Please could you be more clear as to what to change.

**Comment by marciahon29** [comment]
Hello,

I changed as suggested. Unfortunately, I get the same error:

  torch.eq(torch.argmax(self.softmax(total), dim=0), torch.arange(0, batch)))  # correct is a tensor
.../COCA-main-December182023/COCA-main/models/CPC/network/model/model.py:332: UserWarning: Implicit dimension choic
e for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  nce_list.append(torch.sum(torch.diag(self.lsoftmax(total))).item())
.../COCA-main-December182023/COCA-main/models/CPC/network/model/model.py:333: UserWarning: Implicit dimension choic
e for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  nce += torch.sum(torch.diag(self.lsoftmax(total)))  # nce is a tensor

Traceback (most recent call last):
  File "./baseline.py", line 761, in <module>
    main()
  File "./baseline.py", line 701, in main
    train_model(
  File "./baseline.py", line 334, in train_model
    train_scores, test_scores = evaluator.get_predict(
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/merlion/evaluate/anomaly.py", line 433, in get_predict
    train_result, result = super().get_predict(
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/merlion/evaluate/base.py", line 173, in get_predict
    train_result = self._train_model(train_vals, **full_train_kwargs)
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/merlion/evaluate/base.py", line 129, in _train_model
    return self.model.train(train_vals, **train_kwargs)
  File ".../COCA-main-December182023/COCA-main/models/CPC/DetectorModel.py", line 129, in train
    self._train(train_df.values)
  File ".../COCA-main-December182023/COCA-main/models/CPC/DetectorModel.py", line 74, in _train
    snapshot(self.config.logging_dir, 'cpc', {
  File ".../COCA-main-December182023/COCA-main/models/CPC/network/training_v1.py", line 79, in snapshot
    torch.save(state, snapshot_file)
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File ".../ENV_COCA-main-December182023/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './results/cpc/cpc-model_best.pth'

Looking forward to your suggestions.

**Comment by marciahon29** [comment]
In my COCA-main/results/ folder, I only have the folders: "anomaly" and "deepsvdd".

In the "anomaly" folder, I have folders for: RandomCutForest, DeepSVDD, OCSVM, DAGMM, LSTMED, SpectralResideual, and IsolationForest. There is no "CPC" here.

**Comment by marciahon29** [comment]
I solved the problem. It turns out that I have to create the folder "/results/cpc".

**Comment by ruiking04** [comment]
Thanks.
The above folders have been created.
[Modify Details](https://github.com/ruiking04/COCA/commit/ec30e6ecfa67639328ad53bdb1568741de239df3)
